# PART I (Warm-up) :

Q1: Write a Python function that takes an array of integers as an argument and
returns a new array containing only the odd numbers in the original array.

In [21]:
def return_odd_numbers(num_arr):
    odd_num_arr = []
    for num in num_arr:
        if num % 2 != 0:
            odd_num_arr.append(num)
    
    return odd_num_arr

Q2: Create a class called Dog with attributes name and breed. Add a method called
bark that prints a message with the dog's name and a barking sound.

In [24]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
        
    def bark(self):
        print("{}".format(self.name),"bow bow")

Q3. Write a Python program that creates a numpy array of 100 random integers
between 0 and 100, and prints any 2 measures of central tendency and 2 measures
of spread of the array.

In [28]:
import numpy as np

int_arr = np.random.randint(0, 100, size = 100)

print(int_arr)
print("Here are two measures of central tendency of the array: ")
print("Mean:", np.mean(int_arr))
print("Median:", np.median(int_arr))
print(" ")
print("Here are two measures of spread of the array: ")
print("Variance:", np.var(int_arr))
print("Standard deviation:", np.std(int_arr))

[64 91 49 84 27 14 61 85 85  0 37 43 84 19 53 43 40 87 39 55 59 55 82 99
 98 75 23 64 61 50 67 60 23  8  1 85 19 78 93 47 60 29  2 59 22 23 81  9
 88 63 25  9 38 15 29 66 38 19 67  0 67 91 72 74 94 61  7 36 83 25 31 68
  1 30 29 34  8 12  3 88 60 53 71  7 16  3 38 35 42 94 56 25  3 66 33  9
 31 20 19 42]
Here are two measures of central tendency of the array: 
Mean: 45.86
Median: 42.5
 
Here are two measures of spread of the array: 
Variance: 822.0604000000002
Standard deviation: 28.671595700274516


# PART II (Mandatory) :

Q1. Create a class which defines an __init__ function that initializes the class
attribute array. Define another function get_array which takes inputs for the
length of the array and inputs all the elements, and returns its corresponding sorted
array.

In [29]:
class Sort_arr:
    def __init__(self):
        self.arr = []
        
    def get_array(self, length):
        for i in range(length):
            self.arr.append(int(input("Enter element: ")))
        
        return sorted(self.arr)

Q2.
A. Create a 2D array of size 4*4 using list and perform the following
operations:
1. extract the diagonal elements from the array
2. Find the trace of the Matrix
3. Find the max and min element of each row in that matrix
(Hint: convert that 2D list to Numpy Array to make the problem simple)

In [34]:
import numpy as np

arr_1 = [[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]]

arr_1 = np.array(arr_1)

print(arr_1)

print("Diagonal: {}".format(np.diag(arr_1)))

print("Trace: {}".format(np.trace(arr_1)))

print("Max: {}".format(np.max(arr_1, axis = 1)))

print("Min: {}".format(np.min(arr_1, axis = 1)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal: [ 1  6 11 16]
Trace: 34
Max: [ 4  8 12 16]
Min: [ 1  5  9 13]


B. Create another 2D numpy array with shape (4, 5) where each element of the
array is a random float between 0 and 1, inclusive, using numpy's uniform
distribution function. Print the resulting numpy array.

In [42]:
import numpy as np

arr_2 = np.random.uniform(0, 1, size = (4, 4))

print(arr_2)

[[0.54592277 0.3515684  0.49083216 0.18176726]
 [0.95678549 0.24191563 0.2358379  0.66366815]
 [0.41682439 0.92637453 0.52236534 0.25358299]
 [0.27661865 0.12295145 0.01128325 0.24504413]]


C. Multiply the numpy arrays created in Part A and Part B element-wise, and
print the resulting numpy array.

In [45]:
import numpy as np

arr_3 = arr_1 * arr_2

print(arr_3)

[[0.54592277 0.7031368  1.47249648 0.72706903]
 [4.78392744 1.45149379 1.65086529 5.30934522]
 [3.7514195  9.26374531 5.74601869 3.04299587]
 [3.5960424  1.72132035 0.16924878 3.92070607]]


Q3. Write a program that reads in the CSV file containing data on stock prices
(including date, open price, high price, low price, closing price, and volume) and
creates a pandas dataframe with the data. Then, use numpy to calculate the average
closing price for each month and print the results.

In [50]:
import numpy as np
import pandas as pd

dataframe_pandas = pd.read_csv('Data - STOCK_US_XNYS_CSV.csv')

dataframe_pandas['Date'] = pd.to_datetime(dataframe_pandas['Date'])

dataframe_pandas.set_index('Date', inplace=True)

print(dataframe_pandas.resample('M')['Close'].mean())

Date
2022-05-31    39.631111
2022-06-30    39.171429
2022-07-31    40.386000
2022-08-31    38.048696
2022-09-30    33.766667
2022-10-31    30.941429
2022-11-30    24.519524
2022-12-31    26.083810
2023-01-31    30.363000
2023-02-28    32.954211
2023-03-31    31.898696
2023-04-30    28.615789
2023-05-31    28.214000
Freq: M, Name: Close, dtype: float64
